name = "dx11-dxmt"
description = "DX11-games via DXMT graphics stack (doorgaans sneller dan GPTK voor DX11 op Apple Silicon)."

graphics_stack = "dxmt"

[settings]
sync_mode = "msync"
avx_enabled = false
bypass_av_decode = false
gamepad_compat_mode = false
retina_mode = false
metal_hud_enabled = false
metal4_enabled = false
dlss_mode = "disabled"
ray_tracing_mode = "off"
dxmt_experimental_dx12_support = false
molten_vk = "builtin-moltenvk-1.4.2"
open_gl = "builtin-opengl"